#!/usr/bin/env python3
# =============================================================================
# ai_config.py  —  Single API gateway for ai_installer.json
# =============================================================================
# ALL reads and writes to ai_installer.json go through this module.
# No other script — bash or Python — touches the JSON file directly.
#
# Python import usage:
#   import ai_config
#   found, value = ai_config.get("system", "gpu", "torch_cuda")
#   ai_config.set("app", "wan2gp", "status", value="ok")
#   ai_config.record_install("wan2gp", status="ok", python="3.11.9", torch="2.12.0+cu130")
#
# Bash CLI usage:
#   python3 ai_config.py get system gpu torch_cuda
#   python3 ai_config.py get config port
#   python3 ai_config.py set system gpu torch_cuda cu130
#   python3 ai_config.py set app wan2gp status ok
#
#   Exit codes:
#     0  — key found (get) or write succeeded (set)
#     1  — key not found (get) or write failed (set)
#
#   Stdout (get): the value, or empty string if not found
#
# Scopes:
#   system          — machine-wide probe data    → json["probe"]
#   app <name>      — per-app install record     → json["targets"][active_target]["installed"][name]
#   config          — stack-wide settings        → json["config"]
#   meta            — version / approval flags   → json["meta"]
#
# Key segments are positional words — no dots, no JSON paths exposed to callers.
# The mapping from (scope, keys...) to JSON path is owned entirely by this module.
#
# Requires: no third-party packages — stdlib only
# =============================================================================

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# =============================================================================
# JSON file location
# =============================================================================

SCRIPT_DIR = Path(__file__).parent

def _json_path() -> Path:
    env = os.environ.get("AI_INSTALLER_JSON")
    return Path(env) if env else SCRIPT_DIR / "ai_installer.json"


# =============================================================================
# Raw JSON load / write  (private — all access via API functions below)
# =============================================================================

def _skeleton() -> dict:
    """
    Blank v2 JSON structure — all values null.
    Used when creating a new file so nesting always exists.
    null == not yet set. get() treats null as not-found (exit 1).
    Only ai_installer.py --init populates these deliberately.
    """
    return {
        "_comment": "ai_installer — generated by ai_config.py",
        "meta": {
            "version":     "2.0",
            "approved":    None,
            "approved_at": None,
        },
        "config": {
            "port":             None,
            "apps_subdir":      None,
            "resources_subdir": None,
            "outputs_subdir":   None,
            "work_subdir":      None,
            "active_target":    None,
            "python":           {},
            "torch_fallbacks":  {},
        },
        "probe": {
            "probed_at": None,
            "gpu": {
                "name":           None,
                "vram_gb":        None,
                "driver":         None,
                "driver_major":   None,
                "cuda_max":       None,
                "torch_cuda":     None,
                "torch_index":    None,
                "sage_v2_capable": None,
            },
            "tools": {
                "nvcc":       None,
                "nvcc_path":  None,
                "gcc12":      None,
                "git":        None,
                "jq":         None,
                "pyenv":      None,
                "pyenv_root": None,
            },
            "os": {
                "debian":   None,
                "hostname": None,
            },
            "drives": [],
        },
        "targets": {},
    }


def _load() -> dict:
    path = _json_path()
    if path.exists():
        try:
            return json.loads(path.read_text())
        except (json.JSONDecodeError, OSError) as e:
            print(f"[ai_config] ERROR: could not read {path}: {e}", file=sys.stderr)
            return {}
    return {}          # no file yet — callers treat this as empty, not an error


def _save(data: dict) -> bool:
    path = _json_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp  = path.with_suffix(".tmp")
    try:
        tmp.write_text(json.dumps(data, indent=2))
        os.replace(tmp, path)
        return True
    except OSError as e:
        print(f"[ai_config] ERROR: could not write {path}: {e}", file=sys.stderr)
        tmp.unlink(missing_ok=True)
        return False


def _load_or_create() -> dict:
    """
    Load existing JSON or return a fresh skeleton.
    Used by set() and record_install() so writes to a new file
    produce valid complete JSON rather than a sparse partial dict.
    """
    data = _load()
    if not data:
        return _skeleton()
    return data


def _deep_merge(base: dict, overlay: dict) -> dict:
    """Recursively merge overlay into base, returning a new dict."""
    result = dict(base)
    for k, v in overlay.items():
        if k in result and isinstance(result[k], dict) and isinstance(v, dict):
            result[k] = _deep_merge(result[k], v)
        else:
            result[k] = v
    return result


# =============================================================================
# Active target  (used by app scope)
# =============================================================================

def active_target(data: dict | None = None) -> str | None:
    """Return the active target mountpoint from config, or None."""
    d = data if data is not None else _load()
    return d.get("config", {}).get("active_target") or None


# =============================================================================
# Scope → JSON path resolution  (private)
# =============================================================================
# Returns a list of keys to walk into the JSON dict, or None if scope invalid.
# The *keys argument contains the path segments after the scope word.
#
# Scopes:
#   system  [key...]   →  ["probe", key0, key1, ...]
#   app     name [key...]  →  ["targets", <target>, "installed", name, key0, ...]
#   config  [key...]   →  ["config", key0, key1, ...]
#   meta    [key...]   →  ["meta",   key0, key1, ...]

def _resolve_path(scope: str, keys: list[str], data: dict) -> list[str] | None:
    if scope == "system":
        return ["probe"] + keys

    if scope == "app":
        if not keys:
            return None  # need at least app name
        app_name = keys[0]
        target   = active_target(data)
        if not target:
            print("[ai_config] ERROR: no active_target set — run ai_installer.py --init",
                  file=sys.stderr)
            return None
        return ["targets", target, "installed", app_name] + keys[1:]

    if scope in ("config", "meta"):
        return [scope] + keys

    print(f"[ai_config] ERROR: unknown scope '{scope}' — use system / app / config / meta",
          file=sys.stderr)
    return None


# =============================================================================
# _dig / _bury  — walk into / set nested dict by key list  (private)
# =============================================================================

def _dig(data: dict, path: list[str]) -> tuple[bool, object]:
    """
    Walk data by path.
    Returns (True, value) if found and not null.
    Returns (False, None) if any key is missing OR value is null.
    null == not yet set — callers treat it identically to missing.
    """
    node = data
    for key in path:
        if not isinstance(node, dict) or key not in node:
            return False, None
        node = node[key]
    if node is None:
        return False, None
    return True, node


def _bury(data: dict, path: list[str], value: object) -> dict:
    """
    Return a new dict with value set at path, creating intermediate dicts as needed.
    Does not mutate data.
    """
    if not path:
        return value  # type: ignore
    key  = path[0]
    rest = path[1:]
    node = dict(data) if isinstance(data, dict) else {}
    node[key] = _bury(node.get(key, {}), rest, value)
    return node


# =============================================================================
# Public API — Python import interface
# =============================================================================

def get(scope: str, *keys: str) -> tuple[bool, str]:
    """
    Read a value from the JSON by scope and key path.

    Returns:
        (True,  value_as_str)  — key exists
        (False, "")            — key not found or scope error

    Example:
        found, val = ai_config.get("system", "gpu", "torch_cuda")
        found, val = ai_config.get("app", "wan2gp", "status")
        found, val = ai_config.get("config", "port")
    """
    data = _load()
    path = _resolve_path(scope, list(keys), data)
    if path is None:
        return False, ""
    found, value = _dig(data, path)
    if not found:
        return False, ""
    return True, str(value)


def set(scope: str, *keys_and_value) -> bool:
    """
    Write a value to the JSON by scope and key path.
    Last positional argument is always the value.

    Returns True on success, False on failure.

    Example:
        ai_config.set("system", "gpu", "torch_cuda", value="cu130")
        ai_config.set("app", "wan2gp", "status", value="ok")
        ai_config.set("config", "port", value="7860")

    Note: value must be passed as keyword argument to distinguish it from keys.
    """
    if not keys_and_value:
        print("[ai_config] ERROR: set() requires at least one key and a value",
              file=sys.stderr)
        return False

    # Value is the last positional arg; keys are everything before it
    *keys, value = keys_and_value

    data = _load_or_create()
    path = _resolve_path(scope, list(keys), data)
    if path is None:
        return False

    # Coerce common types
    coerced: object = value
    if isinstance(value, str):
        if value.lower() == "true":
            coerced = True
        elif value.lower() == "false":
            coerced = False
        else:
            try:
                coerced = int(value)
            except ValueError:
                try:
                    coerced = float(value)
                except ValueError:
                    coerced = value  # keep as string

    new_data = _bury(data, path, coerced)
    return _save(new_data)


def record_install(app: str, *,
                   status: str = "ok",
                   python: str = "",
                   torch:  str = "",
                   started_at: str = "",
                   duration_min: float = 0.0) -> bool:
    """
    Write an install record for an app under the active target.

    Example:
        ai_config.record_install("wan2gp",
                                 status="ok",
                                 python="3.11.9",
                                 torch="2.12.0+cu130",
                                 started_at="2026-06-02T10:00:00+00:00",
                                 duration_min=43.2)
    """
    data   = _load_or_create()
    target = active_target(data)
    if not target:
        print("[ai_config] ERROR: no active_target — cannot record install for "
              f"'{app}'", file=sys.stderr)
        return False

    now    = datetime.now(timezone.utc).isoformat()
    path   = ["targets", target, "installed", app]
    record = {
        "status":        status,
        "installed_at":  now,
        "started_at":    started_at or now,
        "duration_min":  round(duration_min, 1),
        "python":        python,
        "torch":         torch,
    }
    new_data = _bury(data, path, record)

    # Also append to runs[]
    run_entry = {
        "timestamp":    now,
        "app":          app,
        "status":       status,
        "started_at":   started_at or now,
        "duration_min": round(duration_min, 1),
        "label":        f"{app} {'ok' if status == 'ok' else 'FAILED'}  {round(duration_min, 1)}min",
    }
    runs_path = ["targets", target, "runs"]
    found, existing_runs = _dig(new_data, runs_path)
    runs = list(existing_runs) if found and isinstance(existing_runs, list) else []
    runs.append(run_entry)
    new_data = _bury(new_data, runs_path, runs)

    return _save(new_data)


def record_wheel_build(pkg: str, *,
                       status: str = "ok",
                       wheel_name: str = "",
                       reason: str = "") -> bool:
    """
    Write a wheel build record under the top-level wheel_builds{} section.

    Example:
        ai_config.record_wheel_build("flash_attn", status="ok",
            wheel_name="flash_attn-2.8.3+cu130.torch212-cp311-cp311-linux_x86_64.whl")
        ai_config.record_wheel_build("flash_attn", status="failed",
            reason="gcc ABI mismatch")
    """
    data   = _load_or_create()
    record = {
        "attempted_at": datetime.now(timezone.utc).isoformat(),
        "status":       status,
        "wheel_name":   wheel_name,
        "reason":       reason,
    }
    new_data = _bury(data, ["wheel_builds", pkg], record)
    return _save(new_data)


def write_probe(probe: dict) -> bool:
    """
    Replace the entire probe section with new data.
    Called by ai_installer.py after ai_lib_probe.run().
    """
    data     = _load()
    new_data = _bury(data, ["probe"], probe)
    return _save(new_data)


def write_section(section: str, content: dict) -> bool:
    """
    Replace a top-level section (e.g. 'config', 'meta').
    Used by ai_installer.py --init / --select.
    """
    data     = _load()
    new_data = _bury(data, [section], content)
    return _save(new_data)


def load_all() -> dict:
    """
    Return the full JSON as a dict.
    Use when a caller needs bulk access rather than individual get() calls.
    ai_installer.py uses this at startup.
    """
    return _load()


def save_all(data: dict) -> bool:
    """
    Write the full JSON dict.
    Use for bulk updates (e.g. --init writes the whole structure at once).
    """
    return _save(data)


# =============================================================================
# CLI  — bash interface
# =============================================================================

def _cli_get(args: list[str]) -> int:
    """
    get <scope> <key...> [--default <value>]
    Prints value to stdout.
    Exit 0 if found, 1 if not found (default printed and exit 0 if --default given).
    """
    default     = None
    clean_args  = []
    i = 0
    while i < len(args):
        if args[i] == "--default" and i + 1 < len(args):
            default = args[i + 1]
            i += 2
        else:
            clean_args.append(args[i])
            i += 1

    if not clean_args:
        print("[ai_config] ERROR: get requires scope and at least one key", file=sys.stderr)
        return 1

    scope = clean_args[0]
    keys  = clean_args[1:]

    found, value = get(scope, *keys)
    if found:
        print(value)
        return 0
    if default is not None:
        print(default)
        return 0
    return 1


def _cli_set(args: list[str]) -> int:
    """
    set <scope> <key...> <value>
    Exit 0 on success, 1 on failure.
    """
    if len(args) < 3:
        print("[ai_config] ERROR: set requires scope, at least one key, and a value",
              file=sys.stderr)
        return 1

    scope          = args[0]
    keys_and_value = args[1:]    # last element is the value

    ok = set(scope, *keys_and_value)
    return 0 if ok else 1


def _cli_record_install(args: list[str]) -> int:
    """
    record-install --app <name> --status <s> --python <v> --torch <v>
    """
    import argparse
    p = argparse.ArgumentParser(prog="ai_config.py record-install")
    p.add_argument("--app",    required=True)
    p.add_argument("--status", default="ok")
    p.add_argument("--python", default="")
    p.add_argument("--torch",  default="")
    ns = p.parse_args(args)
    ok = record_install(ns.app, status=ns.status, python=ns.python, torch=ns.torch)
    return 0 if ok else 1


def _cli_record_wheel_build(args: list[str]) -> int:
    """
    record-wheel-build --pkg <name> --status <ok|failed>
                       [--wheel <filename>] [--reason <text>]
    """
    import argparse
    p = argparse.ArgumentParser(prog="ai_config.py record-wheel-build")
    p.add_argument("--pkg",    required=True)
    p.add_argument("--status", default="ok", choices=["ok", "failed"])
    p.add_argument("--wheel",  default="", dest="wheel_name")
    p.add_argument("--reason", default="")
    ns = p.parse_args(args)
    ok = record_wheel_build(ns.pkg, status=ns.status,
                            wheel_name=ns.wheel_name, reason=ns.reason)
    return 0 if ok else 1



    print("""
ai_config.py — JSON API gateway for ai_installer.json

Usage:
  python3 ai_config.py get    <scope> <key...> [--default <value>]
  python3 ai_config.py set    <scope> <key...> <value>
  python3 ai_config.py record-install --app <n> --status <s> --python <v> --torch <v>

Scopes:
  system          machine-wide probe data  (gpu, tools, os, drives)
  app <name>      per-app install record   (status, python, torch, installed_at)
  config          stack settings           (port, subdirs, python versions)
  meta            version / approval       (version, approved, approved_at)

Examples:
  python3 ai_config.py get system gpu torch_cuda
  python3 ai_config.py get system gpu torch_cuda --default cu130
  python3 ai_config.py get app wan2gp status
  python3 ai_config.py get config port
  python3 ai_config.py set app wan2gp status ok
  python3 ai_config.py set config port 7861
  python3 ai_config.py record-install --app wan2gp --status ok --python 3.11.9 --torch 2.12.0+cu130

Exit codes:
  get: 0 = found (or default supplied), 1 = not found
  set: 0 = success, 1 = failure
""")
    return 0


def main() -> None:
    args = sys.argv[1:]
    if not args or args[0] in ("-h", "--help"):
        sys.exit(_cli_help())

    cmd  = args[0]
    rest = args[1:]

    if cmd == "get":
        sys.exit(_cli_get(rest))
    elif cmd == "set":
        sys.exit(_cli_set(rest))
    elif cmd == "record-install":
        sys.exit(_cli_record_install(rest))
    elif cmd == "record-wheel-build":
        sys.exit(_cli_record_wheel_build(rest))
    else:
        print(f"[ai_config] ERROR: unknown command '{cmd}' — use get / set / record-install / record-wheel-build",
              file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
